#!/bin/bash
rm masc_total.txt
cat "masc/masc_wordsense/tools/README.IAtools" >> masc_total.txt
cat "masc/masc_wordsense/tools/calculate-alpha.perl" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/court transcript/Day3PMSession.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/court transcript/Lessig-court-transcript.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/debate-transcript/2nd_Gore-Bush.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/debate-transcript/3rd_Bush-Kerry.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/face-to-face/Bed012.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/face-to-face/Bmr021.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/face-to-face/NapierDianne.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/face-to-face/PolkMaria.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/face-to-face/ReidSandra.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/face-to-face/RindnerBonnie.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/telephone/sw2014-ms98-a-trans.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/telephone/sw2015-ms98-a-trans.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/telephone/sw2025-ms98-a-trans.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/telephone/sw2071-ms98-a-trans.txt" >> masc_total.txt
cat "masc/masc_500k_texts/spoken/telephone/sw2078-ms98-a-trans.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Acephalous-Cant-believe.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Acephalous-Internet.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Anti-Terrorist.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/blog-jet-lag.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/blog-monastery.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/blog-new-year's-resolutions.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/blog-varsity-athletics.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/detroit.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Effing-Idiot.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Fermentation_Eminent-Domain.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Fermentation_HR5034.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/How_soon-Fans.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/How_soon-Lebron-James.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Italy.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/lessig_blog-carbon.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Seedbombing.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/sucker.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Tupelo-Honey-Cafe.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Uprooted_Bike.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/Uprooted_Farming-on-Sand.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/blog/vampires.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/12030.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/12174.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/12176.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/173252.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/173906.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/174124.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/175448.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/175814.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/175816.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/175841.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/176581.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/210343.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/211401.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/211402.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/21257.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/218920.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/219122.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/219123.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/219257.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/221197.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/230685.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/234267.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/234783.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/23559.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/49059.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/50307.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/52201.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/52555.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/52713.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/52998.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/52999.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/53536.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/53555.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/54261.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/54262.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/54263.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/54536.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/54537.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/8885.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/9066.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/9085.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/9159.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/9191.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/ENRON-pearson-email-25jul02.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/enron-thread-159550.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2114716.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2121270.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2125109.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2129640.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2133315.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2137010.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2144868.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2148080.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2152883.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2171003.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2173878.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2180740.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2183485.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-003-2205935.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-034-10062451.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-034-10066763.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-034-10069772.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-034-10073419.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-034-10077455.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-034-10082707.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-11485666.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-11489622.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-11493928.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-11506817.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12119260.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12122969.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12130258.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12133410.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12139072.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12142206.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12146425.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12151335.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12155427.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12158926.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/email/lists-046-12162937.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/A_defense_of_Michael_Moore.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/Ant_Robot.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/anth_essay_4.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/Bartok.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/Black_and_white.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/Homosexuality.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/Madame_White_Snake.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/essays/Ohio_Steel.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/ficlets/1399.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/ficlets/1400.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/ficlets/1401.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/ficlets/1402.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/ficlets/1403.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/fiction/A_Wasted_Day.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/fiction/captured_moments.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/fiction/hotel-california.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/fiction/lw1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/fiction/Nathans_Bylichka.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/fiction/The_Black_Willow.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/govt-docs/chapter-10.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/govt-docs/Env_Prot_Agency-nov1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/govt-docs/fcic_final_report_conclusions.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/govt-docs/Postal_Rate_Comm-ReportToCongress2002WEB.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/govt-docs/Protocol_Regarding_Access.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes10.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes11.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes12.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes13.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes14.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes15.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes16.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes3.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes4.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes5.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes6.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes7.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes8.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/jokes/jokes9.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/Article247_327.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/Article247_328.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/Article247_3500.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/Article247_400.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/Article247_500.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/Article247_66.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/ArticleIP_1059.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/ArticleIP_1060.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/journal/VOL15_3.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/110CYL067.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/110CYL068.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/110CYL069.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/110CYL070.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/110CYL071.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/110CYL072.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/110CYL200.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/112C-L012.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/112C-L013.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/112C-L014.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/112C-L015.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/112C-L016.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/113CWL017.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/113CWL018.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/114CUL057.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/114CUL058.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/114CUL059.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/114CUL060.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/115CVL035.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/115CVL036.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/115CVL037.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/116CUL032.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/116CUL033.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/116CUL034.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/117CWL008.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/117CWL009.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/118CWL048.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/118CWL049.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/118CWL050.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/119CWL041.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/602CZL285.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/alumnifund1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/AMC2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/appalachian1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/aspca1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/att2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/audubon1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/audubon2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/defenders5.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/guidedogs1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/hsus4.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/IFAW1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/littleshelter2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/marine1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/NWF1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/united1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/warner1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/wildelifewatch1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/letters/wwf12.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/movie-script/JurassicParkIV-INT.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/movie-script/JurassicParkIV-Scene_1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/movie-script/JurassicParkIV-Scene_3.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/movie-script/JurassicParkIV-Scene_4.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/movie-script/JurassicParkIV-Scene_5.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/movie-script/pirates.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/20000410_nyt-NEW.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/20000415_apw_eng-NEW.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/20000419_apw_eng-NEW.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/20000424_nyt-NEW.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/20020731-nyt.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/A1.E1-NEW.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/A1.E2-NEW.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire3.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire4.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire5.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire6.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire7.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire8.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/NYTnewswire9.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0006.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0026.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0027.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0032.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0068.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0073.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0106.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0120.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0124.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0127.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0132.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0135.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0136.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0144.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0150.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0151.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0152.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0157.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0158.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0159.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0160.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0161.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0165.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0167.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0168.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0169.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0171.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0172.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0173.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0175.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0176.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0184.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0187.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_0189.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_1640.mrg-NEW.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/newspaper:newswire/wsj_2465.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/non-fiction/ch5.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/non-fiction/chZ.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/non-fiction/CUP1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/non-fiction/CUP2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/non-fiction/rybczynski-ch3.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111344.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111348.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111349.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111359.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111363.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111364.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111367.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111369.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111371.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111373.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111375.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111377.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111380.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111381.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111382.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111393.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111394.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111399.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111400.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111404.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111406.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111410.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111414.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111422.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111424.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111425.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/111428.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114423.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114424.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114428.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114433.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114435.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114439.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114440.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114441.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114442.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114445.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114446.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114447.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114448.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114450.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/114452.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Apply.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Cartoonist_services.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Dear_e-mail_user.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Earnings_Season_Underway.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Fastest_Reader.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/FBI_urgent.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Globa_Professional_Directory.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Laptop_Bags.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Mailbox_Upgrade.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/new_clients.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Re_ Job Offer.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/record_volume.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/Secret_Shopper.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/SEO.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/SgtCassandra.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb10.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb11.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb12.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb14.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb15.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb2.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb20.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb21.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb22.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb23.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb24.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb25.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb26.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb27.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb28.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb29.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb3.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb30.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb31.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb4.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb40.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb41.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb42.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb43.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb44.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb45.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb46.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb47.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb48.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb49.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb50.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb51.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb52.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb53.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb54.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb6.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb8.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/spam/ucb9.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/1468-6708-3-1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/1468-6708-3-3.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/1471-2091-2-9.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/1471-213X-1-1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/1471-230X-2-21.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/journal.pbio.0020001.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/pmed.0010029.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/technical/rr166.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/travel-guides/HistoryGreek.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/travel-guides/HistoryJerusalem.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/travel-guides/HistoryLasVegas.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/travel-guides/IntroDublin.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/travel-guides/IntroHongKong.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/travel-guides/WhatToHongKong.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/travel-guides/WhereToHongKong.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/twitter/tweets1.txt" >> masc_total.txt
cat "masc/masc_500k_texts/written/twitter/tweets2.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/demolish-v/demolish-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/development-n/development-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/history-n/history-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/influence-n/influence-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/launch-v/launch-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/legendary-j/legendary-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/name-v/name-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/order-v/order-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/rule-v/rule-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/successful-j/successful-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/fair-j/fair-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/know-v/know-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/land-n/land-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/long-j/long-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/quiet-j/quiet-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/say-v/say-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/show-v/show-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/tell-v/tell-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/time-n/time-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/work-n/work-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/chance-n/chance-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/cool-j/cool-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/familair-j/familiar-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/forget-v/forget-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/juice-n/juice-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/justify-v/justify-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/player-n/player-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/rapid-j/rapid-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/rip-v/rip-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/try-v/try-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/curious-j/curious-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/entitle-v/entitle-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/exercise-n/exercise-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/exercise-v/exercise-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/mature-v/mature-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/maturity-n/maturity-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/officer-n/officer-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/rate-n/rate-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/smart-j/smart-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/succeed-v/succeed-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/success-n/success-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/succession-n/succession-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/suspicious-j/suspicious-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/become-v/become-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/byzantine-j/byzantine-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/force-n/force-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/greek-j/greek-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/island-n/island-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/part-n/part-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/people-n/people-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/power-n/power-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/transfer-v/transfer-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/write-v/write-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/fair-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/know-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/land-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/long-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/quiet-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-fair-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-know-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-land-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-long-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-quiet-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-say-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-show-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-tell-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-time-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1-work-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/round2.1.alpha-scores.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/say-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/show-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/tell-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/time-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/work-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/fair-j.5ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/know-v.5ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/land-n.6ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/long-j.6ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/quiet-j.6ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-fair-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-know-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-land-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-long-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-quiet-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-say-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-show-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-tell-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-time-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2-work-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/round2.2.alpha-scores.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/say-v.6ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/show-v.5ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/tell-v.5ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/tell-v.6ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/time-n.5ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/work-n.5ann.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/chance-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/cool-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/familiar-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/forget-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/juice-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/justify-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/player-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/rapid-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/rip-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-chance-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-cool-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-familiar-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-forget-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-juice-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-justify-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-player-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-rapid-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-rip-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3-try-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/round3.alpha-scores.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/try-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/curious-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/entitle-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/exercise-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/exercise-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/mature-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/maturity-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/officer-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/rate-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-curious-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-entitle-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-exercise-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-exercise-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-mature-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-maturity-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-officer-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-rate-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-smart-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-succeed-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-success-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-succession-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4-suspicious-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/round4.alpha-scores.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/smart-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/succeed-v.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/success-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/succession-n.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/suspicious-j.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/become-v.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/byzantine-j.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/force-n.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/greek-j.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/island-n.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/part-n.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/people-n.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/power-n.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-become-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-byzantine-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-force-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-greek-j-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-island-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-part-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-people-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-power-n-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-transfer-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5-write-v-sentences.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/round5.alpha-scores.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/transfer-v.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/write-v.masi.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/README.txt" >> masc_total.txt
cat "masc/masc_wordsense/README.txt" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round1/README.round1" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.1/README.data.round2.1" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round2.2/README.round2.2" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round2.2/README.data.round2.2" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round3/README.round3" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round3/README.data.round3" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round4/README.round4" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round4/README.data.round4" >> masc_total.txt
cat "masc/masc_wordsense/data/Full_set/round5/README.round5" >> masc_total.txt
cat "masc/masc_wordsense/data/IAA/round5/README.data.round5" >> masc_total.txt
