insert into problems(index, title, html, answer, release, is_live) values (1, 'Addition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (3, 'Multiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (2, 'Subtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (4, 'Division', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (5, 'Modulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', false);
insert into problems(index, title, html, answer, release, is_live) values (6, 'yAddition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (9, 'yMultiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (8, 'ySubtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (7, 'yDivision', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (10, 'yModulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', false);
insert into problems(index, title, html, answer, release, is_live) values (11, 'x Addition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (13, 'x Multiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (12, 'x Subtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (14, 'x Division', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (15, 'x Modulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', false);
insert into problems(index, title, html, answer, release, is_live) values (16, 'xy Addition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (19, 'xy Multiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (18, 'xy Subtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (17, 'xy Division', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (20, 'xy Modulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', false);
insert into problems(index, title, html, answer, release, is_live) values (21, 'Addition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (23, 'Multiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (22, 'Subtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (24, 'Division', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (25, 'Modulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (26, 'yAddition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (29, 'yMultiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (28, 'ySubtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (27, 'yDivision', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (30, 'yModulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (31, 'x Addition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (33, 'x Multiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (32, 'x Subtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (34, 'x Division', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (35, 'x Modulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (36, 'xy Addition', '<div>What is 1 + 5?</div>', '6', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (39, 'xy Multiplication', '<div>What is 1 * 5?</div>', '5', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (38, 'xy Subtraction', '<div>What is 1 - 5?</div>', '-4', current_timestamp, true);
insert into problems(index, title, html, answer, release, is_live) values (37, 'xy Division', '<div>What is 4 / 2?</div>', '2', '2013-09-06 10:43:05.919402', true);
insert into problems(index, title, html, answer, release, is_live) values (40, 'xy Modulo', '<div>What is 4 % 3?</div>', '1', '2023-08-06 10:43:05.919402', true);

insert into users(username, email, password, is_admin) values ('kevinsogo', 'kevin@kevin.com', '5f4dcc3b5aa765d61d8327deb882cf99', true);
insert into users(username, email, password, is_admin) values ('kevinsogo2', 'kevin2@kevin.com', '5f4dcc3b5aa765d61d8327deb882cf99', false);
insert into users(username, email, password, is_admin) values ('kevinsogo3', 'kevin3@kevin.com', '5f4dcc3b5aa765d61d8327deb882cf99', false);

insert into posts(problem_index, content, author_id, created_at) values (1, 'First post!', 1, current_timestamp);
insert into posts(problem_index, content, author_id, created_at) values (1, 'Second post!', 2, current_timestamp);
insert into posts(problem_index, content, author_id, created_at) values (1, 'Third post!', 3, current_timestamp);
insert into posts(problem_index, content, author_id, created_at) values (11, 'LOL post! This is hard!', 1, current_timestamp);

